create table if not exists public.incidents (
  id bigint generated by default as identity primary key,
  type text not null,
  location text not null,
  lat double precision not null,
  lng double precision not null,
  "timestamp" timestamptz not null default now(),
  status text not null default 'Open',
  severity text not null default 'High',
  verified boolean not null default false,
  description text not null default '',
  panic double precision not null default 0.6
);

create table if not exists public.volunteers (
  id bigint generated by default as identity primary key,
  name text not null,
  lat double precision not null,
  lng double precision not null,
  status text not null,
  eta text not null
);

create table if not exists public.shelters (
  id bigint generated by default as identity primary key,
  name text not null,
  lat double precision not null,
  lng double precision not null,
  capacity text not null
);

create table if not exists public.hospitals (
  id bigint generated by default as identity primary key,
  name text not null,
  lat double precision not null,
  lng double precision not null,
  capacity text not null
);

create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  role text not null,
  full_name text not null,
  phone text,
  email text,
  district text,
  address text,
  emergency_contact text,
  citizen_id text,
  organization text,
  role_title text,
  badge_id text,
  base_location text,
  availability text,
  skills text,
  equipment text,
  designation text,
  department text,
  employee_id text,
  jurisdiction text,
  office_location text,
  access_code_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.incidents enable row level security;
alter table public.volunteers enable row level security;
alter table public.shelters enable row level security;
alter table public.hospitals enable row level security;
alter table public.profiles enable row level security;

create policy "public read incidents" on public.incidents
  for select
  using (true);

create policy "public read volunteers" on public.volunteers
  for select
  using (true);

create policy "public read shelters" on public.shelters
  for select
  using (true);

create policy "public read hospitals" on public.hospitals
  for select
  using (true);

create policy "profiles read own" on public.profiles
  for select
  using (auth.uid() = id);

create policy "profiles update own" on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

alter publication supabase_realtime add table public.incidents;
alter publication supabase_realtime add table public.volunteers;
alter publication supabase_realtime add table public.shelters;
alter publication supabase_realtime add table public.hospitals;
