create table if not exists public.incidents (
  id bigint generated by default as identity primary key,
  type text not null,
  location text not null,
  lat double precision not null,
  lng double precision not null,
  "timestamp" timestamptz not null default now(),
  status text not null default 'Open',
  severity text not null default 'High',
  verified boolean not null default false,
  description text not null default '',
  panic double precision not null default 0.6
);

create table if not exists public.volunteers (
  id bigint generated by default as identity primary key,
  name text not null,
  lat double precision not null,
  lng double precision not null,
  status text not null,
  eta text not null
);

create table if not exists public.shelters (
  id bigint generated by default as identity primary key,
  name text not null,
  lat double precision not null,
  lng double precision not null,
  capacity text not null
);

create table if not exists public.hospitals (
  id bigint generated by default as identity primary key,
  name text not null,
  lat double precision not null,
  lng double precision not null,
  capacity text not null
);

alter table public.incidents enable row level security;
alter table public.volunteers enable row level security;
alter table public.shelters enable row level security;
alter table public.hospitals enable row level security;

create policy "public read incidents" on public.incidents
  for select
  using (true);

create policy "public read volunteers" on public.volunteers
  for select
  using (true);

create policy "public read shelters" on public.shelters
  for select
  using (true);

create policy "public read hospitals" on public.hospitals
  for select
  using (true);

alter publication supabase_realtime add table public.incidents;
alter publication supabase_realtime add table public.volunteers;
alter publication supabase_realtime add table public.shelters;
alter publication supabase_realtime add table public.hospitals;
